# Generated by Django 4.2.6 on 2024-07-01 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('runCliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=20)),
                ('nombreCompleto', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMarca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProveedor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoUsuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=20)),
                ('stockProducto', models.IntegerField()),
                ('descripcionProducto', models.CharField(max_length=100)),
                ('precioProducto', models.IntegerField()),
                ('imagenProducto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremax.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremax.marca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremax.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('idOrden', models.IntegerField()),
                ('idSesion', models.IntegerField()),
                ('direccionPedido', models.CharField(max_length=50)),
                ('fechaPedido', models.DateField()),
                ('totalPedido', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremax.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('runEmpleado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreEmpleado', models.CharField(max_length=20)),
                ('nombreCompleto', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('contraseña', models.CharField(max_length=20)),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremax.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='detallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProducto', models.IntegerField()),
                ('subtotalPedido', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremax.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremax.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ferremax.tipousuario'),
        ),
    ]
