# Generated by Django 4.2.6 on 2024-07-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremax', '0002_estadopedido_pedidosinregistrar_pedido_estadopedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadoPago',
            fields=[
                ('idEstadoPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEstadoPago', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='estadoPago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ferremax.estadopago'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidosinregistrar',
            name='estadoPago',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ferremax.estadopago'),
            preserve_default=False,
        ),
    ]
