# Generated by Django 4.2.6 on 2024-06-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremax', '0002_pedido_detallepedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccionPedido',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
