# Generated by Django 4.2.6 on 2024-07-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremax', '0003_estadopago_pedido_estadopago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombreUsuario',
        ),
    ]
