# Generated by Django 4.2.6 on 2024-07-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferremax', '0004_remove_cliente_nombreusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='nombreEmpleado',
        ),
    ]
